{{- if .Values.configMaps.app.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-config
  namespace: {{ include "trialsage-cer.namespace" . }}
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
data:
  {{- with .Values.configMaps.app.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}