{{- if .Values.rbac.create -}}
---
# API Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trialsage-cer.api.serviceAccountName" . }}
  namespace: {{ include "trialsage-cer.namespace" . }}
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: api
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Worker Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trialsage-cer.worker.serviceAccountName" . }}
  namespace: {{ include "trialsage-cer.namespace" . }}
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: worker
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# ClusterRole for API service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-api
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: api
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
# ClusterRole for Worker service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-worker
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: worker
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
# ClusterRoleBinding for API service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-api
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trialsage-cer.fullname" . }}-api
subjects:
- kind: ServiceAccount
  name: {{ include "trialsage-cer.api.serviceAccountName" . }}
  namespace: {{ include "trialsage-cer.namespace" . }}
---
# ClusterRoleBinding for Worker service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-worker
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    component: worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trialsage-cer.fullname" . }}-worker
subjects:
- kind: ServiceAccount
  name: {{ include "trialsage-cer.worker.serviceAccountName" . }}
  namespace: {{ include "trialsage-cer.namespace" . }}
{{- end }}