{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-secrets
  namespace: {{ include "trialsage-cer.namespace" . }}
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.secrets.stringData.jwt_secret | default (randAlphaNum 32) | quote }}
  {{- if .Values.postgresql.enabled }}
  database_url: {{ include "trialsage-cer.postgresql.connectionString" . | quote }}
  {{- else if .Values.secrets.stringData.database_url }}
  database_url: {{ .Values.secrets.stringData.database_url | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis_url: {{ include "trialsage-cer.redis.connectionString" . | quote }}
  {{- else if .Values.secrets.stringData.redis_url }}
  redis_url: {{ .Values.secrets.stringData.redis_url | quote }}
  {{- end }}
  {{- if .Values.secrets.stringData.aws_access_key }}
  aws_access_key: {{ .Values.secrets.stringData.aws_access_key | quote }}
  {{- end }}
  {{- if .Values.secrets.stringData.aws_secret_key }}
  aws_secret_key: {{ .Values.secrets.stringData.aws_secret_key | quote }}
  {{- end }}
{{- end }}