{{- if .Values.worker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trialsage-cer.fullname" . }}-worker
  namespace: {{ include "trialsage-cer.namespace" . }}
  labels:
    {{- include "trialsage-cer.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.worker.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "trialsage-cer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}