version: "3.9"

services:
  backend:
    build: .
    command: uvicorn ind_automation.main:app --host 0.0.0.0 --port 8002
    env_file: .env
    depends_on: [db, redis]

  worker:
    build: .
    command: celery -A ind_automation.tasks.celery_app worker --loglevel=INFO
    env_file: .env
    depends_on: [backend, redis]

  beat:
    build: .
    command: celery -A ind_automation.tasks.celery_app beat --loglevel=INFO
    env_file: .env
    depends_on: [backend, redis]

  frontend:
    build: ./client
    ports: ["3000:80"]
    environment:
      - VITE_API_URL=http://localhost:8002

  redis:
    image: redis:7-alpine
    volumes: [redis:/data]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes: [pgdata:/var/lib/postgresql/data]

volumes:
  pgdata: {}
  redis: {}
