name: ICH Specialist Service CI

on:
  push:
    paths:
      - 'services/ich_ingest/**'
      - '.github/workflows/ich-specialist-ci.yml'
  pull_request:
    paths:
      - 'services/ich_ingest/**'
      - '.github/workflows/ich-specialist-ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          cd services/ich_ingest
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          flake8 services/ich_ingest --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 services/ich_ingest --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Format check with black
        run: |
          black --check services/ich_ingest
          
      - name: Type check with mypy
        run: |
          mypy --ignore-missing-imports services/ich_ingest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          cd services/ich_ingest
          pip install -r requirements.txt
          
      - name: Test with pytest
        run: |
          pytest services/ich_ingest/tests/ --cov=services.ich_ingest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENV: ${{ secrets.PINECONE_ENV }}
          PINECONE_INDEX: 'ich-specialist-test'